apiVersion: v1
kind: Service
metadata:
  name: app2048
spec:
  selector:
    app: app2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
apiVersion: networking.k8s.io/v1
